---
apiVersion: v1
kind: Service
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: guestbook
  # needed for minikube (not strictly, you can still get it
  # using "minikube service list")
  # externalIPs:
  # - "192.168.99.103"
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-lb-svc
spec:
  selector:
    app: guestbook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer