apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: guestbook
  labels:
    app: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        # image: testlegleux/guestbookapp:2c964de24f72986e04e99b8d0fb3742cde0986cb
        image: legleux/guestbookapp
        ports:
        - containerPort: 5000
        env:
        - name: PG_DBNAME
          value: postgres
        - name: PG_USER
          value: postgres
        # host with helm chart
        - name: PG_HOST
          value: postgres-postgresql.default.svc.cluster.local
        - name: PG_PORT
          value: "5432"
        - name: PG_PASSWORD
          value: password